// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package policy_mock is a generated GoMock package.
package policy_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/wault-pw/alice/pkg/domain"
	policy "github.com/wault-pw/alice/server/policy"
)

// MockUserPolicy is a mock of IUserPolicy interface.
type MockUserPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockUserPolicyMockRecorder
}

// MockUserPolicyMockRecorder is the mock recorder for MockUserPolicy.
type MockUserPolicyMockRecorder struct {
	mock *MockUserPolicy
}

// NewMockUserPolicy creates a new mock instance.
func NewMockUserPolicy(ctrl *gomock.Controller) *MockUserPolicy {
	mock := &MockUserPolicy{ctrl: ctrl}
	mock.recorder = &MockUserPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPolicy) EXPECT() *MockUserPolicyMockRecorder {
	return m.recorder
}

// CanWrite mocks base method.
func (m *MockUserPolicy) CanWrite() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanWrite")
	ret0, _ := ret[0].(error)
	return ret0
}

// CanWrite indicates an expected call of CanWrite.
func (mr *MockUserPolicyMockRecorder) CanWrite() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanWrite", reflect.TypeOf((*MockUserPolicy)(nil).CanWrite))
}

// Wrap mocks base method.
func (m *MockUserPolicy) Wrap(user domain.User) policy.IUserPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", user)
	ret0, _ := ret[0].(policy.IUserPolicy)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockUserPolicyMockRecorder) Wrap(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockUserPolicy)(nil).Wrap), user)
}
