// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: alice_v1.proto

package alice_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User          *RegistrationRequest_User            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Workspace     *RegistrationRequest_Workspace       `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	CardWithItems []*RegistrationRequest_CardWithItems `protobuf:"bytes,3,rep,name=card_with_items,json=cardWithItems,proto3" json:"card_with_items,omitempty"`
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetUser() *RegistrationRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegistrationRequest) GetWorkspace() *RegistrationRequest_Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *RegistrationRequest) GetCardWithItems() []*RegistrationRequest_CardWithItems {
	if x != nil {
		return x.CardWithItems
	}
	return nil
}

type Login0Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *Login0Request) Reset() {
	*x = Login0Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login0Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login0Request) ProtoMessage() {}

func (x *Login0Request) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login0Request.ProtoReflect.Descriptor instead.
func (*Login0Request) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Login0Request) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type Login0Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mutual []byte `protobuf:"bytes,1,opt,name=mutual,proto3" json:"mutual,omitempty"`
	Salt   []byte `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (x *Login0Response) Reset() {
	*x = Login0Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login0Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login0Response) ProtoMessage() {}

func (x *Login0Response) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login0Response.ProtoReflect.Descriptor instead.
func (*Login0Response) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Login0Response) GetMutual() []byte {
	if x != nil {
		return x.Mutual
	}
	return nil
}

func (x *Login0Response) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type Login1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mutual []byte `protobuf:"bytes,1,opt,name=mutual,proto3" json:"mutual,omitempty"`
	Proof  []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *Login1Request) Reset() {
	*x = Login1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login1Request) ProtoMessage() {}

func (x *Login1Request) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login1Request.ProtoReflect.Descriptor instead.
func (*Login1Request) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{3}
}

func (x *Login1Request) GetMutual() []byte {
	if x != nil {
		return x.Mutual
	}
	return nil
}

func (x *Login1Request) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type Login1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proof []byte `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *Login1Response) Reset() {
	*x = Login1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login1Response) ProtoMessage() {}

func (x *Login1Response) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login1Response.ProtoReflect.Descriptor instead.
func (*Login1Response) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{4}
}

func (x *Login1Response) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AedKeyEnc []byte `protobuf:"bytes,1,opt,name=aed_key_enc,json=aedKeyEnc,proto3" json:"aed_key_enc,omitempty"`
	AedKeyTag []byte `protobuf:"bytes,2,opt,name=aed_key_tag,json=aedKeyTag,proto3" json:"aed_key_tag,omitempty"`
	TitleEnc  []byte `protobuf:"bytes,3,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWorkspaceRequest) GetAedKeyEnc() []byte {
	if x != nil {
		return x.AedKeyEnc
	}
	return nil
}

func (x *CreateWorkspaceRequest) GetAedKeyTag() []byte {
	if x != nil {
		return x.AedKeyTag
	}
	return nil
}

func (x *CreateWorkspaceRequest) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

type CreateWorkspaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace *UserWithWorkspace `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
}

func (x *CreateWorkspaceResponse) Reset() {
	*x = CreateWorkspaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceResponse) ProtoMessage() {}

func (x *CreateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorkspaceResponse) GetWorkspace() *UserWithWorkspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type UpsertCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card      *Card       `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	CardItems []*CardItem `protobuf:"bytes,2,rep,name=card_items,json=cardItems,proto3" json:"card_items,omitempty"`
}

func (x *UpsertCardRequest) Reset() {
	*x = UpsertCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCardRequest) ProtoMessage() {}

func (x *UpsertCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCardRequest.ProtoReflect.Descriptor instead.
func (*UpsertCardRequest) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *UpsertCardRequest) GetCardItems() []*CardItem {
	if x != nil {
		return x.CardItems
	}
	return nil
}

type UpsertCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *UpsertCardResponse) Reset() {
	*x = UpsertCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCardResponse) ProtoMessage() {}

func (x *UpsertCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCardResponse.ProtoReflect.Descriptor instead.
func (*UpsertCardResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type CloneCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitleEnc []byte `protobuf:"bytes,1,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
}

func (x *CloneCardRequest) Reset() {
	*x = CloneCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneCardRequest) ProtoMessage() {}

func (x *CloneCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneCardRequest.ProtoReflect.Descriptor instead.
func (*CloneCardRequest) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{9}
}

func (x *CloneCardRequest) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

type CloneCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *CloneCardResponse) Reset() {
	*x = CloneCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneCardResponse) ProtoMessage() {}

func (x *CloneCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneCardResponse.ProtoReflect.Descriptor instead.
func (*CloneCardResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{10}
}

func (x *CloneCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*UserWithWorkspace `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorkspacesResponse) GetItems() []*UserWithWorkspace {
	if x != nil {
		return x.Items
	}
	return nil
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswdSalt []byte `protobuf:"bytes,2,opt,name=passwd_salt,json=passwdSalt,proto3" json:"passwd_salt,omitempty"`
	PrivKeyEnc []byte `protobuf:"bytes,3,opt,name=priv_key_enc,json=privKeyEnc,proto3" json:"priv_key_enc,omitempty"`
	PubKey     []byte `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{12}
}

func (x *WhoAmIResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhoAmIResponse) GetPasswdSalt() []byte {
	if x != nil {
		return x.PasswdSalt
	}
	return nil
}

func (x *WhoAmIResponse) GetPrivKeyEnc() []byte {
	if x != nil {
		return x.PrivKeyEnc
	}
	return nil
}

func (x *WhoAmIResponse) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string   `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Archived    bool     `protobuf:"varint,3,opt,name=archived,proto3" json:"archived,omitempty"`
	TitleEnc    []byte   `protobuf:"bytes,4,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
	TagsEnc     [][]byte `protobuf:"bytes,5,rep,name=tags_enc,json=tagsEnc,proto3" json:"tags_enc,omitempty"`
	CreatedAt   string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{13}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Card) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Card) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

func (x *Card) GetTagsEnc() [][]byte {
	if x != nil {
		return x.TagsEnc
	}
	return nil
}

func (x *Card) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardId   string `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Position int64  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	TitleEnc []byte `protobuf:"bytes,4,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
	BodyEnc  []byte `protobuf:"bytes,5,opt,name=body_enc,json=bodyEnc,proto3" json:"body_enc,omitempty"`
	Hidden   bool   `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
}

func (x *CardItem) Reset() {
	*x = CardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardItem) ProtoMessage() {}

func (x *CardItem) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardItem.ProtoReflect.Descriptor instead.
func (*CardItem) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{14}
}

func (x *CardItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardItem) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardItem) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CardItem) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

func (x *CardItem) GetBodyEnc() []byte {
	if x != nil {
		return x.BodyEnc
	}
	return nil
}

func (x *CardItem) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// Workspace with linked table "user_workspaces",
// which is contain encrypted master kay and auth key
type UserWithWorkspace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OwnerId     string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerPubKey []byte `protobuf:"bytes,4,opt,name=owner_pub_key,json=ownerPubKey,proto3" json:"owner_pub_key,omitempty"`
	WorkspaceId string `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AedKeyEnc   []byte `protobuf:"bytes,6,opt,name=aed_key_enc,json=aedKeyEnc,proto3" json:"aed_key_enc,omitempty"`
	AedKeyTag   []byte `protobuf:"bytes,7,opt,name=aed_key_tag,json=aedKeyTag,proto3" json:"aed_key_tag,omitempty"`
	TitleEnc    []byte `protobuf:"bytes,8,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
	CreatedAt   string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *UserWithWorkspace) Reset() {
	*x = UserWithWorkspace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserWithWorkspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWithWorkspace) ProtoMessage() {}

func (x *UserWithWorkspace) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWithWorkspace.ProtoReflect.Descriptor instead.
func (*UserWithWorkspace) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{15}
}

func (x *UserWithWorkspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserWithWorkspace) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserWithWorkspace) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UserWithWorkspace) GetOwnerPubKey() []byte {
	if x != nil {
		return x.OwnerPubKey
	}
	return nil
}

func (x *UserWithWorkspace) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UserWithWorkspace) GetAedKeyEnc() []byte {
	if x != nil {
		return x.AedKeyEnc
	}
	return nil
}

func (x *UserWithWorkspace) GetAedKeyTag() []byte {
	if x != nil {
		return x.AedKeyTag
	}
	return nil
}

func (x *UserWithWorkspace) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

func (x *UserWithWorkspace) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListCardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Card `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{16}
}

func (x *ListCardsResponse) GetItems() []*Card {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCardItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*CardItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListCardItemsResponse) Reset() {
	*x = ListCardItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCardItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardItemsResponse) ProtoMessage() {}

func (x *ListCardItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardItemsResponse.ProtoReflect.Descriptor instead.
func (*ListCardItemsResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ListCardItemsResponse) GetItems() []*CardItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ArchiveCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archived bool `protobuf:"varint,1,opt,name=archived,proto3" json:"archived,omitempty"`
}

func (x *ArchiveCardResponse) Reset() {
	*x = ArchiveCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveCardResponse) ProtoMessage() {}

func (x *ArchiveCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveCardResponse.ProtoReflect.Descriptor instead.
func (*ArchiveCardResponse) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{18}
}

func (x *ArchiveCardResponse) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type TerminateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{19}
}

func (x *TerminateRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type RegistrationRequest_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver        int32  `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Identity   string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Verifier   []byte `protobuf:"bytes,3,opt,name=verifier,proto3" json:"verifier,omitempty"`
	SrpSalt    []byte `protobuf:"bytes,4,opt,name=srp_salt,json=srpSalt,proto3" json:"srp_salt,omitempty"`
	PasswdSalt []byte `protobuf:"bytes,5,opt,name=passwd_salt,json=passwdSalt,proto3" json:"passwd_salt,omitempty"`
	PrivKeyEnc []byte `protobuf:"bytes,6,opt,name=priv_key_enc,json=privKeyEnc,proto3" json:"priv_key_enc,omitempty"`
	PubKey     []byte `protobuf:"bytes,7,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
}

func (x *RegistrationRequest_User) Reset() {
	*x = RegistrationRequest_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest_User) ProtoMessage() {}

func (x *RegistrationRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest_User.ProtoReflect.Descriptor instead.
func (*RegistrationRequest_User) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegistrationRequest_User) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *RegistrationRequest_User) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *RegistrationRequest_User) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

func (x *RegistrationRequest_User) GetSrpSalt() []byte {
	if x != nil {
		return x.SrpSalt
	}
	return nil
}

func (x *RegistrationRequest_User) GetPasswdSalt() []byte {
	if x != nil {
		return x.PasswdSalt
	}
	return nil
}

func (x *RegistrationRequest_User) GetPrivKeyEnc() []byte {
	if x != nil {
		return x.PrivKeyEnc
	}
	return nil
}

func (x *RegistrationRequest_User) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type RegistrationRequest_Workspace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AedKeyEnc []byte `protobuf:"bytes,1,opt,name=aed_key_enc,json=aedKeyEnc,proto3" json:"aed_key_enc,omitempty"`
	TitleEnc  []byte `protobuf:"bytes,2,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
}

func (x *RegistrationRequest_Workspace) Reset() {
	*x = RegistrationRequest_Workspace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest_Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest_Workspace) ProtoMessage() {}

func (x *RegistrationRequest_Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest_Workspace.ProtoReflect.Descriptor instead.
func (*RegistrationRequest_Workspace) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RegistrationRequest_Workspace) GetAedKeyEnc() []byte {
	if x != nil {
		return x.AedKeyEnc
	}
	return nil
}

func (x *RegistrationRequest_Workspace) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

type RegistrationRequest_CardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitleEnc []byte `protobuf:"bytes,1,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
	BodyEnc  []byte `protobuf:"bytes,2,opt,name=body_enc,json=bodyEnc,proto3" json:"body_enc,omitempty"`
	Hidden   bool   `protobuf:"varint,3,opt,name=hidden,proto3" json:"hidden,omitempty"`
}

func (x *RegistrationRequest_CardItem) Reset() {
	*x = RegistrationRequest_CardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest_CardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest_CardItem) ProtoMessage() {}

func (x *RegistrationRequest_CardItem) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest_CardItem.ProtoReflect.Descriptor instead.
func (*RegistrationRequest_CardItem) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RegistrationRequest_CardItem) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

func (x *RegistrationRequest_CardItem) GetBodyEnc() []byte {
	if x != nil {
		return x.BodyEnc
	}
	return nil
}

func (x *RegistrationRequest_CardItem) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type RegistrationRequest_CardWithItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitleEnc []byte                          `protobuf:"bytes,1,opt,name=title_enc,json=titleEnc,proto3" json:"title_enc,omitempty"`
	TagsEnc  [][]byte                        `protobuf:"bytes,2,rep,name=tags_enc,json=tagsEnc,proto3" json:"tags_enc,omitempty"`
	Items    []*RegistrationRequest_CardItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RegistrationRequest_CardWithItems) Reset() {
	*x = RegistrationRequest_CardWithItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_v1_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest_CardWithItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest_CardWithItems) ProtoMessage() {}

func (x *RegistrationRequest_CardWithItems) ProtoReflect() protoreflect.Message {
	mi := &file_alice_v1_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest_CardWithItems.ProtoReflect.Descriptor instead.
func (*RegistrationRequest_CardWithItems) Descriptor() ([]byte, []int) {
	return file_alice_v1_proto_rawDescGZIP(), []int{0, 3}
}

func (x *RegistrationRequest_CardWithItems) GetTitleEnc() []byte {
	if x != nil {
		return x.TitleEnc
	}
	return nil
}

func (x *RegistrationRequest_CardWithItems) GetTagsEnc() [][]byte {
	if x != nil {
		return x.TagsEnc
	}
	return nil
}

func (x *RegistrationRequest_CardWithItems) GetItems() []*RegistrationRequest_CardItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_alice_v1_proto protoreflect.FileDescriptor

var file_alice_v1_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x22, 0xe0, 0x05, 0x0a, 0x13, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x36, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x09, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x53, 0x0a, 0x0f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x6c, 0x69,
	0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x57, 0x69,
	0x74, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x57, 0x69, 0x74,
	0x68, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xc6, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x72, 0x70,
	0x5f, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x72, 0x70,
	0x53, 0x61, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x5f, 0x73,
	0x61, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x64, 0x53, 0x61, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x76, 0x5f, 0x6b, 0x65,
	0x79, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x1a,
	0x48, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0b,
	0x61, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x61, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x1a, 0x5a, 0x0a, 0x08, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x65,
	0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45,
	0x6e, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6f, 0x64, 0x79, 0x45, 0x6e, 0x63, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68,
	0x69, 0x64, 0x64, 0x65, 0x6e, 0x1a, 0x85, 0x01, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x64, 0x57, 0x69,
	0x74, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x5f, 0x65, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x45, 0x6e, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x73, 0x5f, 0x65, 0x6e, 0x63,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x63, 0x12,
	0x3c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2b, 0x0a,
	0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x30, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x3c, 0x0a, 0x0e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x75,
	0x74, 0x75, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x22, 0x3d, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x75, 0x74,
	0x75, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x75, 0x74, 0x75, 0x61,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x26, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22,
	0x75, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x65, 0x64,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x61, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x65, 0x64,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x61, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x22, 0x54, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x39, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x6a, 0x0a, 0x11,
	0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x31, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x6c, 0x69, 0x63,
	0x65, 0x5f, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x63,
	0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x38, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61,
	0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x22, 0x2f, 0x0a, 0x10, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f,
	0x65, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x45, 0x6e, 0x63, 0x22, 0x37, 0x0a, 0x11, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x4b, 0x0a, 0x16,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x7c, 0x0a, 0x0e, 0x57, 0x68, 0x6f,
	0x41, 0x6d, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x64, 0x5f, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x53, 0x61, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0c,
	0x70, 0x72, 0x69, 0x76, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0xac, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x61, 0x67, 0x73, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07,
	0x74, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x45, 0x6e, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x65, 0x6e,
	0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6f, 0x64, 0x79, 0x45, 0x6e, 0x63,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x22, 0x9a, 0x02, 0x0a, 0x11, 0x55, 0x73, 0x65,
	0x72, 0x57, 0x69, 0x74, 0x68, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x65, 0x64,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x61, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x65, 0x64,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x61, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x39, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x6c, 0x69, 0x63,
	0x65, 0x5f, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x41, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65,
	0x5f, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x31, 0x0a, 0x13, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x22, 0x2e, 0x0a, 0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x0f, 0x5a, 0x0d, 0x64, 0x65, 0x73, 0x63, 0x2f, 0x61,
	0x6c, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alice_v1_proto_rawDescOnce sync.Once
	file_alice_v1_proto_rawDescData = file_alice_v1_proto_rawDesc
)

func file_alice_v1_proto_rawDescGZIP() []byte {
	file_alice_v1_proto_rawDescOnce.Do(func() {
		file_alice_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_alice_v1_proto_rawDescData)
	})
	return file_alice_v1_proto_rawDescData
}

var file_alice_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_alice_v1_proto_goTypes = []interface{}{
	(*RegistrationRequest)(nil),               // 0: alice_v1.RegistrationRequest
	(*Login0Request)(nil),                     // 1: alice_v1.Login0Request
	(*Login0Response)(nil),                    // 2: alice_v1.Login0Response
	(*Login1Request)(nil),                     // 3: alice_v1.Login1Request
	(*Login1Response)(nil),                    // 4: alice_v1.Login1Response
	(*CreateWorkspaceRequest)(nil),            // 5: alice_v1.CreateWorkspaceRequest
	(*CreateWorkspaceResponse)(nil),           // 6: alice_v1.CreateWorkspaceResponse
	(*UpsertCardRequest)(nil),                 // 7: alice_v1.UpsertCardRequest
	(*UpsertCardResponse)(nil),                // 8: alice_v1.UpsertCardResponse
	(*CloneCardRequest)(nil),                  // 9: alice_v1.CloneCardRequest
	(*CloneCardResponse)(nil),                 // 10: alice_v1.CloneCardResponse
	(*ListWorkspacesResponse)(nil),            // 11: alice_v1.ListWorkspacesResponse
	(*WhoAmIResponse)(nil),                    // 12: alice_v1.WhoAmIResponse
	(*Card)(nil),                              // 13: alice_v1.Card
	(*CardItem)(nil),                          // 14: alice_v1.CardItem
	(*UserWithWorkspace)(nil),                 // 15: alice_v1.UserWithWorkspace
	(*ListCardsResponse)(nil),                 // 16: alice_v1.ListCardsResponse
	(*ListCardItemsResponse)(nil),             // 17: alice_v1.ListCardItemsResponse
	(*ArchiveCardResponse)(nil),               // 18: alice_v1.ArchiveCardResponse
	(*TerminateRequest)(nil),                  // 19: alice_v1.TerminateRequest
	(*RegistrationRequest_User)(nil),          // 20: alice_v1.RegistrationRequest.User
	(*RegistrationRequest_Workspace)(nil),     // 21: alice_v1.RegistrationRequest.Workspace
	(*RegistrationRequest_CardItem)(nil),      // 22: alice_v1.RegistrationRequest.CardItem
	(*RegistrationRequest_CardWithItems)(nil), // 23: alice_v1.RegistrationRequest.CardWithItems
}
var file_alice_v1_proto_depIdxs = []int32{
	20, // 0: alice_v1.RegistrationRequest.user:type_name -> alice_v1.RegistrationRequest.User
	21, // 1: alice_v1.RegistrationRequest.workspace:type_name -> alice_v1.RegistrationRequest.Workspace
	23, // 2: alice_v1.RegistrationRequest.card_with_items:type_name -> alice_v1.RegistrationRequest.CardWithItems
	15, // 3: alice_v1.CreateWorkspaceResponse.workspace:type_name -> alice_v1.UserWithWorkspace
	13, // 4: alice_v1.UpsertCardRequest.card:type_name -> alice_v1.Card
	14, // 5: alice_v1.UpsertCardRequest.card_items:type_name -> alice_v1.CardItem
	13, // 6: alice_v1.UpsertCardResponse.card:type_name -> alice_v1.Card
	13, // 7: alice_v1.CloneCardResponse.card:type_name -> alice_v1.Card
	15, // 8: alice_v1.ListWorkspacesResponse.items:type_name -> alice_v1.UserWithWorkspace
	13, // 9: alice_v1.ListCardsResponse.items:type_name -> alice_v1.Card
	14, // 10: alice_v1.ListCardItemsResponse.items:type_name -> alice_v1.CardItem
	22, // 11: alice_v1.RegistrationRequest.CardWithItems.items:type_name -> alice_v1.RegistrationRequest.CardItem
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_alice_v1_proto_init() }
func file_alice_v1_proto_init() {
	if File_alice_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alice_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login0Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login0Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkspaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkspaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkspacesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoAmIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserWithWorkspace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCardItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest_Workspace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest_CardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_v1_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest_CardWithItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alice_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alice_v1_proto_goTypes,
		DependencyIndexes: file_alice_v1_proto_depIdxs,
		MessageInfos:      file_alice_v1_proto_msgTypes,
	}.Build()
	File_alice_v1_proto = out.File
	file_alice_v1_proto_rawDesc = nil
	file_alice_v1_proto_goTypes = nil
	file_alice_v1_proto_depIdxs = nil
}
