on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download
        run: go mod download

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Compile WASM
        run: make build:wasm

      - name: Upload WASM binary
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/

  wasm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download WASM binary
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: build/

      - name: Install modules
        run: yarn --cwd js install

      - name: Test
        run: yarn --cwd js run test
